config:
  backup: true
  create: true
  chmod_on_import: true
  dotpath: dotfiles-user
dotfiles:
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
    chmod: '644'
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
    chmod: '644'
  f_gtkrc-2.0:
    src: gtkrc-2.0
    dst: ~/.gtkrc-2.0
    chmod: '644'
  d_fish:
    src: config/fish
    dst: ~/.config/fish
    chmod: '700'
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
    chmod: '755'
  f_octaverc:
    src: octaverc
    dst: ~/.octaverc
    chmod: '644'
profiles:
  garuda:
    dotfiles:
    - f_vimrc
    - f_gitconfig
    - f_gtkrc-2.0
    - d_fish
    - d_kitty
    - f_octaverc
